
# Valid TradingView widget timezones.
TIMEZONES = {'UTC': 'Etc/UTC',
             'Exchange': 'exchange',
             'Honolulu': 'Pacific/Honolulu',
             'Juneau': 'America/Juneau',
             'Los Angeles': 'America/Los_Angeles',
             'Phoenix': 'America/Phoenix',
             'Vancouver': 'America/Vancouver',
             'San Salvador': 'America/El_Salvador',
             'Bogota': 'America/Bogota',
             'Chicago': 'America/Chicago',
             'Lima': 'America/Lima',
             'Mexico City': 'America/Mexico_City',
             'Caracas': 'America/Caracas',
             'New York': 'America/New_York',
             'Toronto': 'America/Toronto',
             'Buenos Aires': 'America/Argentina/Buenos_Aires',
             'Santiago': 'America/Santiago',
             'Sao Paulo': 'America/Sao_Paulo',
             'Reykjavik': 'Atlantic/Reykjavik',
             'Lagos': 'Africa/Lagos',
             'London': 'Europe/London',
             'Belgrade': 'Europe/Belgrade',
             'Berlin': 'Europe/Berlin',
             'Cairo': 'Africa/Cairo',
             'Copenhagen': 'Europe/Copenhagen',
             'Johannesburg': 'Africa/Johannesburg',
             'Luxembourg': 'Europe/Luxembourg',
             'Madrid': 'Europe/Madrid',
             'Paris': 'Europe/Paris',
             'Rome': 'Europe/Rome',
             'Stockholm': 'Europe/Stockholm',
             'Warsaw': 'Europe/Warsaw',
             'Zurich': 'Europe/Zurich',
             'Athens': 'Europe/Athens',
             'Bahrain': 'Asia/Bahrain',
             'Helsinki': 'Europe/Helsinki',
             'Istanbul': 'Europe/Istanbul',
             'Jerusalem': 'Asia/Jerusalem',
             'Kuwait': 'Asia/Kuwait',
             'Moscow': 'Europe/Moscow',
             'Qatar': 'Asia/Qatar',
             'Riga': 'Europe/Riga',
             'Riyadh': 'Asia/Riyadh',
             'Tallinn': 'Europe/Tallinn',
             'Vilnius': 'Europe/Vilnius',
             'Dubai': 'Asia/Dubai',
             'Muscat': 'Asia/Muscat',
             'Tehran': 'Asia/Tehran',
             'Ashkhabad': 'Asia/Ashkhabad',
             'Kolkata': 'Asia/Kolkata',
             'Almaty': 'Asia/Almaty',
             'Bangkok': 'Asia/Bangkok',
             'Ho Chi Minh': 'Asia/Ho_Chi_Minh',
             'Jakarta': 'Asia/Jakarta',
             'Chongqing': 'Asia/Chongqing',
             'Hong Kong': 'Asia/Hong_Kong',
             'Shanghai': 'Asia/Shanghai',
             'Singapore': 'Asia/Singapore',
             'Taipei': 'Asia/Taipei',
             'Seoul': 'Asia/Seoul',
             'Tokyo': 'Asia/Tokyo',
             'Adelaide': 'Australia/Adelaide',
             'Brisbane': 'Australia/Brisbane',
             'Sydney': 'Australia/Sydney',
             'Norfolk Island': 'Pacific/Norfolk',
             'New Zealand': 'Pacific/Auckland',
             'Chatham Islands': 'Pacific/Chatham',
             'Tokelau': 'Pacific/Fakaofo'}

# Valid TradingView widget intervals.
INTERVALS = {'1m': '1',
             '3m': '3',
             '5m': '5',
             '15m': '15',
             '30m': '30',
             '1h': '60',
             '2h': '120',
             '3h': '180',
             '4h': '240',
             '1d': 'D',
             '1w': 'W'}

# Valid TradingView widget bar styles.
BARSTYLES = {'Bars': '0',
             'Candles': '1',
             'Hollow_Candles': '2',
             'Heikin_Ashi': '3',
             'Line': '4',
             'Area': '5',
             'Renko': '6',
             'Line_Break': '7',
             'Kagi': '8',
             'Point_and_Figure': '9'}

# Valid TradingView widget themes.
THEMES = ['Dark', 'Light']
