
# Valid TradingView widget timezones.
TIMEZONES = {'UTC': 'Etc/UTC',
             'Exchange': 'exchange',
             'Honolulu': 'Pacific/Honolulu',
             'Juneau': 'America/Juneau',
             'Los Angeles': 'America/Los_Angeles',
             'Phoenix': 'America/Phoenix',
             'Vancouver': 'America/Vancouver',
             'San Salvador': 'America/El_Salvador',
             'Bogota': 'America/Bogota',
             'Chicago': 'America/Chicago',
             'Lima': 'America/Lima',
             'Mexico City': 'America/Mexico_City',
             'Caracas': 'America/Caracas',
             'New York': 'America/New_York',
             'Toronto': 'America/Toronto',
             'Buenos Aires': 'America/Argentina/Buenos_Aires',
             'Santiago': 'America/Santiago',
             'Sao Paulo': 'America/Sao_Paulo',
             'Reykjavik': 'Atlantic/Reykjavik',
             'Lagos': 'Africa/Lagos',
             'London': 'Europe/London',
             'Belgrade': 'Europe/Belgrade',
             'Berlin': 'Europe/Berlin',
             'Cairo': 'Africa/Cairo',
             'Copenhagen': 'Europe/Copenhagen',
             'Johannesburg': 'Africa/Johannesburg',
             'Luxembourg': 'Europe/Luxembourg',
             'Madrid': 'Europe/Madrid',
             'Paris': 'Europe/Paris',
             'Rome': 'Europe/Rome',
             'Stockholm': 'Europe/Stockholm',
             'Warsaw': 'Europe/Warsaw',
             'Zurich': 'Europe/Zurich',
             'Athens': 'Europe/Athens',
             'Bahrain': 'Asia/Bahrain',
             'Helsinki': 'Europe/Helsinki',
             'Istanbul': 'Europe/Istanbul',
             'Jerusalem': 'Asia/Jerusalem',
             'Kuwait': 'Asia/Kuwait',
             'Moscow': 'Europe/Moscow',
             'Qatar': 'Asia/Qatar',
             'Riga': 'Europe/Riga',
             'Riyadh': 'Asia/Riyadh',
             'Tallinn': 'Europe/Tallinn',
             'Vilnius': 'Europe/Vilnius',
             'Dubai': 'Asia/Dubai',
             'Muscat': 'Asia/Muscat',
             'Tehran': 'Asia/Tehran',
             'Ashkhabad': 'Asia/Ashkhabad',
             'Kolkata': 'Asia/Kolkata',
             'Almaty': 'Asia/Almaty',
             'Bangkok': 'Asia/Bangkok',
             'Ho Chi Minh': 'Asia/Ho_Chi_Minh',
             'Jakarta': 'Asia/Jakarta',
             'Chongqing': 'Asia/Chongqing',
             'Hong Kong': 'Asia/Hong_Kong',
             'Shanghai': 'Asia/Shanghai',
             'Singapore': 'Asia/Singapore',
             'Taipei': 'Asia/Taipei',
             'Seoul': 'Asia/Seoul',
             'Tokyo': 'Asia/Tokyo',
             'Adelaide': 'Australia/Adelaide',
             'Brisbane': 'Australia/Brisbane',
             'Sydney': 'Australia/Sydney',
             'Norfolk Island': 'Pacific/Norfolk',
             'New Zealand': 'Pacific/Auckland',
             'Chatham Islands': 'Pacific/Chatham',
             'Tokelau': 'Pacific/Fakaofo'}

# Valid TradingView widget intervals.
INTERVALS = {'1m': '1',
             '3m': '3',
             '5m': '5',
             '15m': '15',
             '30m': '30',
             '1h': '60',
             '2h': '120',
             '3h': '180',
             '4h': '240',
             '1d': 'D',
             '1w': 'W'}

# Valid TradingView widget bar styles.
BARSTYLES = {'Bars': '0',
             'Candles': '1',
             'Hollow_Candles': '2',
             'Heikin_Ashi': '3',
             'Line': '4',
             'Area': '5',
             'Renko': '6',
             'Line_Break': '7',
             'Kagi': '8',
             'Point_and_Figure': '9'}

# Valid TradingView widget themes.
THEMES = ['Dark', 'Light']

# Valid TradingView widget studies.
STUDIES ={'accd':'ACCD@tv-basicstudies',
        'studyadr':'studyADR@tv-basicstudies',
        'aroon':'AROON@tv-basicstudies',
        'atr':'ATR@tv-basicstudies',
        'awesomeoscillator':'AwesomeOscillator@tv-basicstudies',
        'bb':'BB@tv-basicstudies',
        'bollingerbandsr':'BollingerBandsR@tv-basicstudies',
        'bollingerbandswidth':'BollingerBandsWidth@tv-basicstudies',
        'cmf':'CMF@tv-basicstudies',
        'chaikinoscillator':'ChaikinOscillator@tv-basicstudies',
        'chandemo':'chandeMO@tv-basicstudies',
        'choppinessindex':'ChoppinessIndex@tv-basicstudies',
        'cci':'CCI@tv-basicstudies',
        'crsi':'CRSI@tv-basicstudies',
        'correlationcoefficient':'CorrelationCoefficient@tv-basicstudies',
        'detrendedpriceoscillator':'DetrendedPriceOscillator@tv-basicstudies',
        'dm':'DM@tv-basicstudies',
        'donch':'DONCH@tv-basicstudies',
        'doubleema':'DoubleEMA@tv-basicstudies',
        'easeofmovement':'EaseOfMovement@tv-basicstudies',
        'efi':'EFI@tv-basicstudies',
        'env':'ENV@tv-basicstudies',
        'fishertransform':'FisherTransform@tv-basicstudies',
        'hv':'HV@tv-basicstudies',
        'hullma':'hullMA@tv-basicstudies',
        'ichimokucloud':'IchimokuCloud@tv-basicstudies',
        'kltnr':'KLTNR@tv-basicstudies',
        'kst':'KST@tv-basicstudies',
        'linearregression':'LinearRegression@tv-basicstudies',
        'macd':'MACD@tv-basicstudies',
        'mom':'MOM@tv-basicstudies',
        'mf':'MF@tv-basicstudies',
        'moonphases':'MoonPhases@tv-basicstudies',
        'masimple':'MASimple@tv-basicstudies',
        'maexp':'MAExp@tv-basicstudies',
        'maweighted':'MAWeighted@tv-basicstudies',
        'obv':'OBV@tv-basicstudies',
        'psar':'PSAR@tv-basicstudies',
        'pivotpointshighlow':'PivotPointsHighLow@tv-basicstudies',
        'pivotpointsstandard':'PivotPointsStandard@tv-basicstudies',
        'priceosc':'PriceOsc@tv-basicstudies',
        'pricevolumetrend':'PriceVolumeTrend@tv-basicstudies',
        'roc':'ROC@tv-basicstudies',
        'rsi':'RSI@tv-basicstudies',
        'vigorindex':'VigorIndex@tv-basicstudies',
        'volatilityindex':'VolatilityIndex@tv-basicstudies',
        'smiergodicindicator':'SMIErgodicIndicator@tv-basicstudies',
        'smiergodicoscillator':'SMIErgodicOscillator@tv-basicstudies',
        'stochastic':'Stochastic@tv-basicstudies',
        'stochasticrsi':'StochasticRSI@tv-basicstudies',
        'tripleema':'TripleEMA@tv-basicstudies',
        'trix':'Trix@tv-basicstudies',
        'ultimateosc':'UltimateOsc@tv-basicstudies',
        'vstop':'VSTOP@tv-basicstudies',
        'volume':'Volume@tv-basicstudies',
        'vwap':'VWAP@tv-basicstudies',
        'mavolumeweighted':'MAVolumeWeighted@tv-basicstudies',
        'williamr':'WilliamR@tv-basicstudies',
        'williamsalligator':'WilliamsAlligator@tv-basicstudies',
        'williamsfractal':'WilliamsFractal@tv-basicstudies',
        'zigzag':'ZigZag@tv-basicstudies'}
